[tools]
dotnet = "latest"
go = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"
yarn = "latest"

"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:tsgolint" = "latest"
"npm:turbo" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
